folio-org/ui-finc-config

translations/ui-finc-config/pt_BR.json

Update translation strings as of 20190513T134002

---

translations/ui-finc-config/ar.json
translations/ui-finc-config/ca.json
translations/ui-finc-config/da.json
translations/ui-finc-config/de.json
translations/ui-finc-config/en_GB.json
translations/ui-finc-config/en_SE.json
translations/ui-finc-config/en_US.json
translations/ui-finc-config/es.json
translations/ui-finc-config/es_419.json
translations/ui-finc-config/es_ES.json
translations/ui-finc-config/fr.json
translations/ui-finc-config/fr_FR.json
translations/ui-finc-config/hu.json
translations/ui-finc-config/it_IT.json
translations/ui-finc-config/pt_BR.json
translations/ui-finc-config/pt_PT.json
translations/ui-finc-config/zh_CN.json

Update translation strings as of 20190522T140747

---

translations/ui-finc-config/ar.json
translations/ui-finc-config/ca.json
translations/ui-finc-config/da.json
translations/ui-finc-config/de.json
translations/ui-finc-config/en_GB.json
translations/ui-finc-config/en_SE.json
translations/ui-finc-config/en_US.json
translations/ui-finc-config/es.json
translations/ui-finc-config/es_419.json
translations/ui-finc-config/es_ES.json
translations/ui-finc-config/fr.json
translations/ui-finc-config/fr_FR.json
translations/ui-finc-config/hu.json
translations/ui-finc-config/it_IT.json
translations/ui-finc-config/pt_BR.json
translations/ui-finc-config/pt_PT.json
translations/ui-finc-config/zh_CN.json

Update translation strings as of 20190606T155546

---

translations/ui-finc-config/ar.json
translations/ui-finc-config/ca.json
translations/ui-finc-config/da.json
translations/ui-finc-config/de.json
translations/ui-finc-config/en_GB.json
translations/ui-finc-config/en_SE.json
translations/ui-finc-config/en_US.json
translations/ui-finc-config/es.json
translations/ui-finc-config/es_419.json
translations/ui-finc-config/es_ES.json
translations/ui-finc-config/fr.json
translations/ui-finc-config/fr_FR.json
translations/ui-finc-config/hu.json
translations/ui-finc-config/it_IT.json
translations/ui-finc-config/pt_BR.json
translations/ui-finc-config/pt_PT.json
translations/ui-finc-config/zh_CN.json

Update translation strings as of 20190801T134041

---

translations/ui-finc-config/zh_CN.json

Update translation strings as of 20190909T193700

---

translations/ui-finc-config/ca.json
translations/ui-finc-config/da.json
translations/ui-finc-config/de.json
translations/ui-finc-config/en_GB.json
translations/ui-finc-config/en_SE.json
translations/ui-finc-config/en_US.json
translations/ui-finc-config/es.json
translations/ui-finc-config/es_419.json
translations/ui-finc-config/es_ES.json
translations/ui-finc-config/fr.json
translations/ui-finc-config/fr_FR.json
translations/ui-finc-config/hu.json
translations/ui-finc-config/pt_PT.json

Update translation strings as of 20190925T125755

---

translations/ui-finc-config/zh_CN.json

Update translation strings as of 20191022T162142

---

translations/ui-finc-config/fr_FR.json

Update translation strings as of 20191119T231120

---

translations/ui-finc-config/fr_FR.json
translations/ui-finc-config/ru.json

Update translation strings as of 20191202T021928

---

translations/ui-finc-config/es_ES.json

Update translation strings as of 20191218T142024

---

translations/ui-finc-config/fr_FR.json

Update translation strings as of 20200117T173544

---

translations/ui-finc-config/ar.json
translations/ui-finc-config/ca.json
translations/ui-finc-config/da.json
translations/ui-finc-config/de.json
translations/ui-finc-config/en_GB.json
translations/ui-finc-config/en_SE.json
translations/ui-finc-config/en_US.json
translations/ui-finc-config/es.json
translations/ui-finc-config/es_419.json
translations/ui-finc-config/es_ES.json
translations/ui-finc-config/fr.json
translations/ui-finc-config/fr_FR.json
translations/ui-finc-config/he.json
translations/ui-finc-config/hu.json
translations/ui-finc-config/it_IT.json
translations/ui-finc-config/ja.json
translations/ui-finc-config/pt_BR.json
translations/ui-finc-config/pt_PT.json
translations/ui-finc-config/ru.json
translations/ui-finc-config/zh_CN.json
translations/ui-finc-config/zh_TW.json

Update translation strings as of 20200206T141023

---

translations/ui-finc-config/es_419.json
translations/ui-finc-config/fr_FR.json

Update translation strings as of 20200211T224145

---

translations/ui-finc-config/ar.json
translations/ui-finc-config/ca.json
translations/ui-finc-config/da.json
translations/ui-finc-config/de.json
translations/ui-finc-config/en_GB.json
translations/ui-finc-config/en_SE.json
translations/ui-finc-config/en_US.json
translations/ui-finc-config/es.json
translations/ui-finc-config/es_419.json
translations/ui-finc-config/es_ES.json
translations/ui-finc-config/fr.json
translations/ui-finc-config/fr_FR.json
translations/ui-finc-config/he.json
translations/ui-finc-config/hu.json
translations/ui-finc-config/it_IT.json
translations/ui-finc-config/ja.json
translations/ui-finc-config/pt_BR.json
translations/ui-finc-config/pt_PT.json
translations/ui-finc-config/ru.json
translations/ui-finc-config/ur.json
translations/ui-finc-config/zh_CN.json
translations/ui-finc-config/zh_TW.json

Update translation strings as of 20200217T172736

---

translations/ui-finc-config/ar.json

Update translation strings as of 20200224T151433

---

translations/ui-finc-config/zh_TW.json

Update translation strings as of 20200424T193712

---

translations/ui-finc-config/zh_TW.json

Update translation strings as of 20200428T150732

---

translations/ui-finc-config/ru.json

Update translation strings as of 20200602T151309

---

translations/ui-finc-config/ar.json
translations/ui-finc-config/ca.json
translations/ui-finc-config/da.json
translations/ui-finc-config/de.json
translations/ui-finc-config/en_GB.json
translations/ui-finc-config/en_SE.json
translations/ui-finc-config/en_US.json
translations/ui-finc-config/es.json
translations/ui-finc-config/es_419.json
translations/ui-finc-config/es_ES.json
translations/ui-finc-config/fr.json
translations/ui-finc-config/fr_FR.json
translations/ui-finc-config/he.json
translations/ui-finc-config/hu.json
translations/ui-finc-config/it_IT.json
translations/ui-finc-config/ja.json
translations/ui-finc-config/pt_BR.json
translations/ui-finc-config/pt_PT.json
translations/ui-finc-config/ru.json
translations/ui-finc-config/ur.json
translations/ui-finc-config/zh_CN.json
translations/ui-finc-config/zh_TW.json

Update translation strings as of 20200623T182030

---

translations/ui-finc-config/ru.json

Update translation strings as of 20200624T182544

---

translations/ui-finc-config/ar.json
translations/ui-finc-config/ca.json
translations/ui-finc-config/da.json
translations/ui-finc-config/de.json
translations/ui-finc-config/en_GB.json
translations/ui-finc-config/en_SE.json
translations/ui-finc-config/en_US.json
translations/ui-finc-config/es.json
translations/ui-finc-config/es_419.json
translations/ui-finc-config/es_ES.json
translations/ui-finc-config/fr.json
translations/ui-finc-config/fr_FR.json
translations/ui-finc-config/he.json
translations/ui-finc-config/hu.json
translations/ui-finc-config/it_IT.json
translations/ui-finc-config/ja.json
translations/ui-finc-config/pt_BR.json
translations/ui-finc-config/pt_PT.json
translations/ui-finc-config/ru.json
translations/ui-finc-config/ur.json
translations/ui-finc-config/zh_CN.json
translations/ui-finc-config/zh_TW.json

Update translation strings as of 20200701T150841

---

translations/ui-finc-config/ar.json
translations/ui-finc-config/ca.json
translations/ui-finc-config/da.json
translations/ui-finc-config/de.json
translations/ui-finc-config/en_GB.json
translations/ui-finc-config/en_SE.json
translations/ui-finc-config/en_US.json
translations/ui-finc-config/es.json
translations/ui-finc-config/es_419.json
translations/ui-finc-config/es_ES.json
translations/ui-finc-config/fr.json
translations/ui-finc-config/fr_FR.json
translations/ui-finc-config/he.json
translations/ui-finc-config/hu.json
translations/ui-finc-config/it_IT.json
translations/ui-finc-config/ja.json
translations/ui-finc-config/pt_BR.json
translations/ui-finc-config/pt_PT.json
translations/ui-finc-config/ru.json
translations/ui-finc-config/ur.json
translations/ui-finc-config/zh_CN.json
translations/ui-finc-config/zh_TW.json

Update translation strings as of 20200707T213422

---

translations/ui-finc-config/ca.json
translations/ui-finc-config/da.json
translations/ui-finc-config/de.json
translations/ui-finc-config/en_SE.json
translations/ui-finc-config/en_US.json
translations/ui-finc-config/fr.json
translations/ui-finc-config/he.json
translations/ui-finc-config/hu.json
translations/ui-finc-config/ja.json
translations/ui-finc-config/pt_PT.json
translations/ui-finc-config/ru.json
translations/ui-finc-config/ur.json

Update translation strings as of 20200709T123052

---

translations/ui-finc-config/pt_BR.json

Update translation strings as of 20200710T132222

---

translations/ui-finc-config/fr_FR.json

Update translation strings as of 20200716T140311

---

translations/ui-finc-config/zh_CN.json

Update translation strings as of 20200721T202356

---

translations/ui-finc-config/ar.json
translations/ui-finc-config/ca.json
translations/ui-finc-config/da.json
translations/ui-finc-config/de.json
translations/ui-finc-config/en_GB.json
translations/ui-finc-config/en_SE.json
translations/ui-finc-config/en_US.json
translations/ui-finc-config/es.json
translations/ui-finc-config/es_419.json
translations/ui-finc-config/es_ES.json
translations/ui-finc-config/fr.json
translations/ui-finc-config/fr_FR.json
translations/ui-finc-config/he.json
translations/ui-finc-config/hu.json
translations/ui-finc-config/it_IT.json
translations/ui-finc-config/ja.json
translations/ui-finc-config/pt_BR.json
translations/ui-finc-config/pt_PT.json
translations/ui-finc-config/ru.json
translations/ui-finc-config/ur.json
translations/ui-finc-config/zh_CN.json
translations/ui-finc-config/zh_TW.json

Update translation strings as of 20200723T031126

---

translations/ui-finc-config/ar.json
translations/ui-finc-config/ca.json
translations/ui-finc-config/da.json
translations/ui-finc-config/de.json
translations/ui-finc-config/en_GB.json
translations/ui-finc-config/en_SE.json
translations/ui-finc-config/en_US.json
translations/ui-finc-config/es.json
translations/ui-finc-config/es_419.json
translations/ui-finc-config/es_ES.json
translations/ui-finc-config/fr.json
translations/ui-finc-config/fr_FR.json
translations/ui-finc-config/he.json
translations/ui-finc-config/hu.json
translations/ui-finc-config/it_IT.json
translations/ui-finc-config/ja.json
translations/ui-finc-config/pt_BR.json
translations/ui-finc-config/pt_PT.json
translations/ui-finc-config/ru.json
translations/ui-finc-config/ur.json
translations/ui-finc-config/zh_CN.json
translations/ui-finc-config/zh_TW.json

Update translation strings as of 20200901T173106

---

translations/ui-finc-config/ar.json
translations/ui-finc-config/ca.json
translations/ui-finc-config/da.json
translations/ui-finc-config/de.json
translations/ui-finc-config/en_GB.json
translations/ui-finc-config/en_SE.json
translations/ui-finc-config/en_US.json
translations/ui-finc-config/es.json
translations/ui-finc-config/es_419.json
translations/ui-finc-config/es_ES.json
translations/ui-finc-config/fr.json
translations/ui-finc-config/fr_FR.json
translations/ui-finc-config/he.json
translations/ui-finc-config/hi_IN.json
translations/ui-finc-config/hu.json
translations/ui-finc-config/it_IT.json
translations/ui-finc-config/ja.json
translations/ui-finc-config/ko.json
translations/ui-finc-config/pl.json
translations/ui-finc-config/pt_BR.json
translations/ui-finc-config/pt_PT.json
translations/ui-finc-config/ru.json
translations/ui-finc-config/ur.json
translations/ui-finc-config/zh_CN.json
translations/ui-finc-config/zh_TW.json

Update translation strings as of 20201007T133333

---

translations/ui-finc-config/fr_FR.json

Update translation strings as of 20201020T221939

---

translations/ui-finc-config/it_IT.json
translations/ui-finc-config/ja.json

Update translation strings as of 20201105T151643

---

translations/ui-finc-config/fr_FR.json

Update translation strings as of 20201110T192302

---

translations/ui-finc-config/it_IT.json

Update translation strings as of 20201111T142927

---

translations/ui-finc-config/ber.json
translations/ui-finc-config/ca.json
translations/ui-finc-config/da.json
translations/ui-finc-config/de.json
translations/ui-finc-config/fr.json
translations/ui-finc-config/fr_FR.json
translations/ui-finc-config/he.json
translations/ui-finc-config/hi_IN.json
translations/ui-finc-config/hu.json
translations/ui-finc-config/it_IT.json
translations/ui-finc-config/ja.json
translations/ui-finc-config/ko.json
translations/ui-finc-config/pl.json
translations/ui-finc-config/pt_BR.json
translations/ui-finc-config/pt_PT.json
translations/ui-finc-config/ru.json
translations/ui-finc-config/ur.json
translations/ui-finc-config/zh_TW.json

Update translation strings as of 20201119T214636

---

translations/ui-finc-config/ar.json
translations/ui-finc-config/ja.json

Update translation strings as of 20201124T212804

---

.eslintrc
package.json
test/bigtest/.eslintrc.js

https://issues.folio.org/browse/UIFC-269

UIFC-269-replace-babel-eslint

---

package.json
src/routes/SourcesRoute.js

https://issues.folio.org/browse/UIFC-297

UIFC-297: no results shown on first open

---

jest.config.js
package.json
src/components/MetadataSources/SourceManagement/Contact/ContactFieldArray.js

https://issues.folio.org/browse/UIFC-295

UIFC-295: upgrade stripes-erm-components

---

src/components/MetadataCollections/MetadataCollectionForm.js
src/components/MetadataCollections/MetadataCollectionView.js
src/components/MetadataCollections/MetadataCollections.js
src/components/MetadataSources/MetadataSourceForm.js
src/components/MetadataSources/MetadataSourceView.js
src/components/MetadataSources/MetadataSources.js

https://issues.folio.org/browse/UIFC-337

UIFC-337-remove-deprecated-properties

---

CHANGELOG.md
src/routes/CollectionsRoute.js
src/routes/SourcesRoute.js

https://folio-org.atlassian.net/browse/UIFC-375

UIFC-375: fix update resources bug

---

CHANGELOG.md
package.json
src/components/MetadataCollections/MetadataCollectionForm.test.js
src/components/MetadataSources/MetadataSourceForm.test.js
test/jest/__mock__/currencyData.mock.js
test/jest/__mock__/index.js
test/jest/__mock__/matchMedia.mock.js
test/jest/__mock__/reactIntl.mock.js
test/jest/__mock__/stripesConfig.mock.js
test/jest/__mock__/stripesCore.mock.js
test/jest/__mock__/stripesIcon.mock.js
test/jest/__mock__/stripesSmartComponents.mock.js

https://folio-org.atlassian.net/browse/UIFC-378

UIFC-378: Fix tests

---

CHANGELOG.md
package.json
src/components/MetadataSources/MetadataSourceForm.js
src/components/MetadataSources/SourceManagement/Contact/ContactFieldArray.js
src/components/MetadataSources/SourceManagement/Contact/ContactFieldArray.test.js
src/components/MetadataSources/SourceManagement/Contact/EditCard.js
src/components/MetadataSources/SourceManagement/Contact/EditCard/EditCard.js
src/components/MetadataSources/SourceManagement/Contact/EditCard/EditCard.test.js
src/components/MetadataSources/SourceManagement/Contact/EditCard/editcard-util.js
src/components/MetadataSources/SourceManagement/Contact/contact-util.js
src/components/MetadataSources/SourceManagement/Contact/contact-util.test.js
src/components/MetadataSources/SourceManagement/SourceManagementForm.test.js

https://folio-org.atlassian.net/browse/UIFC-365

UIFC-365: Remove dependencies of k int and stripes erm components

---

CHANGELOG.md
package.json

https://folio-org.atlassian.net/browse/UIFC-384
See https://github.com/folio-org/mod-finc-config/pull/152

[UIFC-384] Update required interfaces

---

CHANGELOG.md
package.json

https://folio-org.atlassian.net/browse/UIFC-394
* Updates permissions
See https://github.com/folio-org/mod-finc-config/pull/154

[UIFC-394] Update permissions

---

CHANGELOG.md
src/components/DisplayUtils/urls.js
src/components/MetadataCollections/MetadataCollections.js
src/components/MetadataSources/MetadataSources.js
src/components/Navigation/FincNavigation.js

https://folio-org.atlassian.net/browse/UIFC-400

UIFC-400: Restructure SASQ and localStorage

---

CHANGELOG.md
src/components/DisplayUtils/EditCard/EditCard.test.js
src/components/MetadataCollections/MetadataCollectionForm.test.js
src/components/MetadataCollections/MetadataCollectionView.test.js
src/components/MetadataCollections/MetadataCollections.js
src/components/MetadataCollections/MetadataCollections.test.js
src/components/MetadataSources/MetadataSourceForm.test.js
src/components/MetadataSources/MetadataSourceView.test.js
src/components/MetadataSources/MetadataSources.js
src/components/MetadataSources/MetadataSources.test.js
src/components/MetadataSources/SourceManagement/Contact/ContactFieldArray.test.js
src/components/MetadataSources/SourceManagement/SourceManagementForm.test.js
src/index.test.js
src/routes/CollectionsRoute.test.js
src/routes/SourcesRoute.test.js
src/settings/IsilSettings.test.js
test/jest/helpers/renderWithIntlConfiguration.js

https://folio-org.atlassian.net/browse/UIFC-401

UIFC-401: Add tests for SASQ

---

CHANGELOG.md
src/index.test.js
src/routes/CollectionCreateRoute.test.js
src/routes/CollectionEditRoute.test.js
src/routes/CollectionViewRoute.test.js
src/routes/CollectionsRoute.test.js
src/routes/SourceCreateRoute.test.js
src/routes/SourceEditRoute.test.js
src/routes/SourceViewRoute.test.js
src/routes/SourcesRoute.test.js
test/fixtures/routeProps.js

https://folio-org.atlassian.net/browse/UIFC-402

UIFC-402: Fix index.test.js

---

CHANGELOG.md
package.json

https://folio-org.atlassian.net/browse/UIFC-429
* Add support for `finc-config-isils 2.0` interace

[UIFC-429] Support `finc-config-isils 2.0` interace

---

CHANGELOG.md
src/components/MetadataCollections/filterConfigData.js

https://folio-org.atlassian.net/browse/UIFC-432

UIFC-432: Use full-text search
